### ISSUE TITLE
No way to navigate back to 2018/2019 editions once in 2017

### ISSUE THREAD

**Issue by lirantal** [jsheroes/jsheroes.io#160]
Once you navigated to https://2017.jsheroes.io there's no easy way to go back to any other edition due to the old website design.

**Comment by alexnm** [comment]
would be a bit tricky, since we need to redeploy the old site, have to see who can do that. what if we open 2017 in a new tab? what do you think?

**Comment by danielmocan** [comment]
The solution for this is simple, we just need to add the information  from 2017 edition to jsheroes.io main repo (we do the same with 2018). If nobody takes this until the weekend, I will take care of it.
