### ISSUE TITLE
Add new ambassadors

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#182]
Let's add: Jeremias and Ives to the ambassadors section on the website

We need the details first:
- photo
- position/company

**Comment by jeremenichelli** [comment]
👋 

Photo 👉 https://drive.google.com/file/d/1h6a6c1zy2P8H3fzzj-0e-MfUPhSmmb7o/view?usp=sharing
Position 👉 Front end engineer in Design Systems
