### ISSUE TITLE
Speaker's page layout

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#183]
Between 768px and 1000px layout is all messed up
<img width="889" alt="screen shot 2018-08-17 at 21 14 57" src="https://user-images.githubusercontent.com/9945366/44282109-a1cf1d00-a262-11e8-806e-4eea52db8f85.png">

**Comment by SaraVieira** [comment]
U no like?

**Comment by alexnm** [comment]
it has that Picasso look

**Comment by alexnm** [comment]
@SaraVieira will you take this in the coming days? I can ask someone else to have a look if you're busy, no worries

**Comment by SaraVieira** [comment]
I can do it tomorrow when I am back home :)
