### ISSUE TITLE
Find a responsive friendly solution for the updates section

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#184]
Check screenshot on small widths
<img width="427" alt="screen shot 2018-08-18 at 11 22 03" src="https://user-images.githubusercontent.com/9945366/44297374-f9a86b00-a2d8-11e8-8442-0dd29d985ace.png">

**Comment by SaraVieira** [comment]
Hey!

Maybe a scroll? It never breaks and goes 100% I'm width?

**Comment by alexnm** [comment]
you mean horizontal scroll? maybe we can also replace the text with icons on smaller devices?
