### ISSUE TITLE
Add a new section with tweeter feed

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#192]
Add some tweets, manually, which are representative for each of the past editons. look for #jsheroes hashtag.

Depending on how it looks and how it may work, we can think of adding one to the main page

**Comment by aleretegan** [comment]
![twitter feed example](https://user-images.githubusercontent.com/19417706/52174361-2d018800-279b-11e9-8f39-047c38c7c9d5.PNG)
Design example
