### ISSUE TITLE
Integrate lazysizes for image optimization

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#208]
We could/should
- load webp/jpeg2000 alternative images to classic jpeg
- lazyload below the fold images
- create responsive images with at least 2 breakpoints (mobile/desktop)

The lazyload part is nicely supported by lazysizes: https://github.com/aFarkas/lazysizes

**Comment by jonattfin** [comment]
webp will be available in firefox 65 which will be launched at the end of Jan 2019. https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/65
