### ISSUE TITLE
We should change the way we do styling

### ISSUE THREAD

**Issue by danielmocan** [jsheroes/jsheroes.io#212]
I think that styled JSX is a mess.
We should find another way to style our components.

Any suggestions?

**Comment by dgonzalezr** [comment]
What about [styled-components](https://www.styled-components.com/) ?

**Comment by alexnm** [comment]
does anyone want/have time to take this head first? it seems like a lot of work with not that much benefit. @danielmocan the decision is yours if we're keeping this as an open discussion or not. styled-jsx can get messy, but if we work with clearly defined components it does the job well imo

**Comment by danielmocan** [comment]
@alexnm I know that now we have our hands full, but I would at least move this ticket to backlog and we could tackle it when we have free time.
Do we have a backlog :) ?

**Comment by alexnm** [comment]
no, but you can create one as a milestone with no due date
