### ISSUE TITLE
Create contact form

### ISSUE THREAD

**Issue by danielmocan** [jsheroes/jsheroes.io#213]
We have a contact link in the navigation. Currently its just a link to mailto… I was thinking its not user friendly ( most of the users would expect to be redirect to a form ), so I was thinking we should create a contact form page.

What do you guys think ?

**Comment by alexnm** [comment]
this needs a bit of backend support (sending emails)

**Comment by danielmocan** [comment]
I can do this, but it will not be ready for the November release.

**Comment by jonattfin** [comment]
I can work on this, will be done in aprox ~ 1 week. What do you think about this design?
https://screenshots.firefox.com/KRiEwB1oJX3BXFyq/info.ecosia.org#

**Comment by alexnm** [comment]
@danielmocan @ciprian-iacob I know you talked about the "backend" part. can you check with @jonattfin on how to proceed with this feature?

**Comment by danielmocan** [comment]
@alexnm  I spoke with @ciprian-iacob, but we did not reached a conclusion on what platform to use( AWS or something else ). We should first see what we should move to backend and make a structure before start working on something.
We are open to suggestions @alexnm @jonattfin or anyone else

**Comment by jonattfin** [comment]
@danielmocan, @alexnm , @ciprian-iacob 

I was thinking to use https://www.mailjet.com, they have an free tier allowing to send 6000 emails / month. We just do the form & send the request to them.
https://www.mailjet.com/pricing/
https://www.mailjet.com/email-api/

Your thoughts on that?

**Comment by danielmocan** [comment]
@jonattfin Looks good, at least we can use this until we have a proper backend( it will probably take a while :) ).

**Comment by jonattfin** [comment]
In the end i ended up using https://sendgrid.com, see in my PR.
