### ISSUE TITLE
Photo Galleries from each year

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#215]
It would be great to have a link from each year with the selected photos from that event (on dropbox?)

**Comment by alexnm** [comment]
we can use these links:
- 2018 - https://www.facebook.com/pg/jsheroes/photos/?tab=album&album_id=2044909715746934
- 2017 - https://www.facebook.com/pg/jsheroes/photos/?tab=album&album_id=1903947609843146

and we can extract a bunch of images to use directly on the website, with links to the entire albums

**Comment by claudmi** [comment]
Attached the design for desktop and mobile. Let's add the Gallery **above the Organizers** section.

- The links to the buttons are:
2018 PHOTOS: https://www.facebook.com/pg/jsheroes/photos/?tab=album&album_id=2044909715746934
2018 VIDEOS: https://www.youtube.com/playlist?list=PLB9NqTp0uKrRn_C80xQK8QEeO-vaBmN_9
2017 PHOTOS: https://www.facebook.com/pg/jsheroes/photos/?tab=album&album_id=1903947609843146

- The link underline should appear on mouseover.


![gallery-desktop-1920px-section](https://user-images.githubusercontent.com/210512/50047702-87e40080-00c3-11e9-8628-13844a6eff57.png)

![gallery-mobile- 750px-section](https://user-images.githubusercontent.com/210512/50047703-87e40080-00c3-11e9-95a4-6f1a5bf63d95.png)

- The gallery should stretch accross the entire screen width like this:
![image](https://user-images.githubusercontent.com/210512/50047781-09885e00-00c5-11e9-8373-6e599a9242ba.png)

**Comment by alexnm** [comment]
amazing work @claudmi ;D

**Comment by jonattfin** [comment]
really nice :-) @claudmi

**Comment by jonattfin** [comment]
Hey @claudmi, can you put also an design with some siblings... for example previous & next sections. I want to be sure i got it right. Thx.
