### ISSUE TITLE
Adopt a JavaScripter page redesign

### ISSUE THREAD

**Issue by claudmi** [jsheroes/jsheroes.io#227]
Redesigned the /adopt-a-jser page, to be more in tune with the rest of the redesigned pages.
Attached:
- mockups for desktop and mobile
- photos used

**FYI:** The text for the ADOPT part should be visible.
The text for the PHOTO CONTEST part should be hidden for now, until we decide to launch contest.

Here is the text in the mockups (it's slightly updated from what we had earlier this year):

**Learn About the Adopt a JavaScripter Couch-Surfing Program**

**Adopt a JavaScripter**

If you want to be "adopted" by one of our Cluj JavaScripters during the **JSHeroes conference**, you can use our "Adopt a JavaScripter" couch-surfing program.
We will pair you up with a **Host** or a **Guest** that we think is ok for you, according to the info you filled in the application forms.
Apply if you want to be a Guest, or if you are from Cluj-Napoca apply to be a Host.

**JSHeroes PHOTO CONTEST**

You are participating in the “Adopt a JavaScripter” couch-surfing program? Then enter the JSHeroes photo contest for a chance to win **2 free tickets** to the JSHeroes conference. 
How does the contest work?
Take a photo with yourself and your Host or Guest.
Then post it on Twitter with the hashtag **#adoptajavascripter**.
The winner will be selected randomly using random.org.
Post your photos until April 9, 2019.
Pretty simple!

![adopt-page-redesign](https://user-images.githubusercontent.com/210512/47180764-00c81580-d32a-11e8-9b76-f6794f7a6bbb.png)
![adopt-page-mobile](https://user-images.githubusercontent.com/210512/47181198-0f62fc80-d32b-11e8-961e-0f6e121a34ae.png)

![jsheroes-adopt-jser-photo](https://user-images.githubusercontent.com/210512/47180651-af1f8b00-d329-11e8-98e1-adbe7f63f4e8.jpg)

![adopt-photo](https://user-images.githubusercontent.com/210512/47180400-31f41600-d329-11e8-85b6-0cc411511db4.png)

**Comment by jonattfin** [comment]
Hello @claudmi,
Is there a chance to upload the mockups to Zeplin (https://zeplin.io/) ? If you didn't used it before, is a awesome tool to share designs between designers & devs. Check this short intro: https://www.youtube.com/watch?time_continue=59&v=tbKZAGthUgQ

I've already created an project in Zeplin & sent you an invitation to it / on your email. You just have to download their windows/mac app, & upload the design files (using photoshop or sketch). Zeplin will then do the rest. We can talk on slack for clarifications
Thx.

**Comment by jonattfin** [comment]
[Zeplin link](https://zpl.io/agPQLeD)

**Comment by jonattfin** [comment]
@claudmi Should the buttons do something?
