### ISSUE TITLE
Review and Refactor current agenda implementation

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#240]
In preparation for January when we start putting talks on the agenda, we need to have a look at the current implementation and maybe check if refactoring actions or redoing parts of it are needed.

Some thing which should be handled differently:
- agenda items might start at different times (we plan for both 20 and 30 minute slots for 2019)
- agenda items with two speakers are implemented in a hacky way
- agenda items with no speaker should be easily created (ex: panel discussion, lightning talks, welcome speech, etc)
- buttons for workshop items should be revisited (but ticket/sold out)

**Comment by ecris87** [comment]
Looking into this. 

@alexnm , when you get the chance can you give me more details in regards to the last item:
"buttons for workshop items should be revisited (buy ticket/sold out)". Do you mean a new UI?
