### ISSUE TITLE
Update the org team

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#242]
The team is listed here: https://jsheroes.io/organizers

Alexandra Minzat should be added as: "Operations Manager"
We should also add the new website volunteers: @ciprian-iacob, @catalinonutu3 and @ecris87 (we need your details)
Also Ana Cojuhari's role can be changed to "Bannerman".
Alin Pausan can be moved into the still friends category.

All the details can be asked on slack if we don't have the photos/twitter handles from everyone

**Comment by jonattfin** [comment]
progress 75%

**Comment by jonattfin** [comment]
done
