### ISSUE TITLE
Add Metrics to Become a sponsor page and the metrics widget on homepage

### ISSUE THREAD

**Issue by aleretegan** [jsheroes/jsheroes.io#257]
As discussed with @danielmocan  and @alexnm we have a list of metrics to be added on the website. Initially we thought about adding them on Become a sponsor page but the idea of adding  a widget on homepage is also taken into account. Please decide and use the following content in the beginning:
FUTURE - add icons ? bulleted list would be a good start though
Check if design is also needed and speak to Claudia if the case.

----
Some key metrics about us and our results so far: 
No of volunteers in organising team - 18
No of ambassadors - 8
**Attendees:**
No of attendees in 2017 (1st edition) - 450
No of attendees in 2018 - 600
		-other nationalities (besides romanian people) - 20.3 %
Expected no. of attendees in 2019 - 700
**Social media reach:**
Youtube data:
Subscribers - 672
Views - more than 28 300 ( lifetime )
Hours of content watched - more than 2460 ( lifetime )
Twitter followers - 1.639 ( and counting)
Facebook page followers - 1.106
Facebook Community Group -  1.313
Meetup.com members - 1.543 ( we get around 30 new members each month )
No of people reached in November 2018 on FB - 40 K (eg: ad for Early Bird tickets)

**Comment by ana-cojuhari** [comment]
I suggest writing the numbers with "K"s. To be modified: 

- Views - more than 28.3K (lifetime)
-  Hours of content watched - more than 2.5K (lifetime)
- Twitter followers - 1.6K (and counting)
- Facebook page followers - 1.1K
- Facebook Community Group - 1.3K
- Meetup.com members - 1.5K (we get around 30 new members each month)

Please add:

- Over 1K tweets on Twitter
- 300+ CfP applications for JSHeroes 2019

**Comment by jonattfin** [comment]
@danielmocan Isn't this done?

**Comment by danielmocan** [comment]
@jonattfin Yes, I left it open because I had to add them on the become a sponsor page. ( But done that meanwhile )
