### ISSUE TITLE
Going back to selected tab after opening a speaker page from schedule

### ISSUE THREAD

**Issue by elizamaria** [jsheroes/jsheroes.io#282]
Actual: From Home page, going to Schedule, select tab 'Workshops', select first speaker from the first workshop then navigate back will take me to the 'Day 1' schedule. 

Expected: when going back from speaker page to keep being on the 'Workshops' tab.

**Comment by alexnm** [comment]
we need a way to keep the selectedtab in the url (maybe an anchor?)
