### ISSUE TITLE
Add extra white spacing below the stats area

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#284]
![screenshot 2018-12-29 at 11 03 35](https://user-images.githubusercontent.com/9945366/50536085-6c640580-0b59-11e9-8c45-9daf4d8432d3.png)

**Comment by ecris87** [comment]
I can take this, it's also something i've noticed and wanted to fix :)

**Comment by alexnm** [comment]
lol, that was quick :)

**Comment by alexnm** [comment]
@ecris87 please check when @jonattfin merges his photo gallery branch, as the photo section comes right there above the Organizers

**Comment by alexnm** [comment]
done, it was merged

**Comment by ecris87** [comment]
thanks, PR is now open.
