### ISSUE TITLE
Static brochure link doesn't work

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#296]
Looks like something is wrong with serving the static asset? or something is wrong with the pdf? please investigate

https://jsheroes.io/static/brochure.pdf

It is located in the static folder in the project. It should just work as a static asset, does not pass through next.js

**Comment by jeremenichelli** [comment]
It's working here

**Comment by catalinonutu3** [comment]
Works fine with chome & osx as well.

**Comment by lirantal** [comment]
@alexnm I bet the issue is the service worker that is caching it incorrectly for you.
Can you unregister it and clear the page cache and try to reload?

**Comment by ecris87** [comment]
It's working fine for me in Firefox and Chrome v70. I managed to reproduce it in Chrome v71 (i updated from v70 to v71 which is the latest official build). In Chrome Canary (v73) it works. Very strange.

If the service worker is unregistered indeed it works but that is not a final solution (if the user visits jsheroes.io => sw is registered => visiting the brochure page again will result in the same behaviour). @lirantal @alexnm If help is needed i can also look into this later tonight.

**Comment by lirantal** [comment]
Go ahead and work on that, if you can. I'll un-assign myself.
Obviously once something is cached with the SW you can't force unregister it for clients but I think that this is the culprit.

**Comment by ecris87** [comment]
Found a similar issue logged for gatsbyjs: https://github.com/gatsbyjs/gatsby/issues/10899
It appears this is a chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=918944
I'll try implementing a workaround.

**Comment by ecris87** [comment]
@lirantal you were right, sw was the issue (with root cause being a chrome bug). Good catch! PR is now open.

**Comment by jeremenichelli** [comment]
Great work Emilia!
