### ISSUE TITLE
Create Sticker Contest page

### ISSUE THREAD

**Issue by claudmi** [jsheroes/jsheroes.io#308]
Create a page for the Sticker Contest. Could be called .../sticker-contest
Designs are on Zeplin: https://zpl.io/beoArXp
Here is the text in case it helps:

**The creative brief**
JSHeroes is an **open-source** community event, this means we rely on the free time and skills of the community to organize the event each year. We are currently preparing the 3rd edition taking place in April 11-12, 2019.
We love everything related to communities, and **we love stickers** - we collect them, trade them, and sometime even stick them on our laptops. Some of us like to use them on mugs and T-shirts, whatever the case, we love these things!
Our aim is to expand our pool of stickers with new and creative ones that people would love to use.
The people we reach are web/software developers, UI/UX designers.

**Prizes**
**1st** PRIZE: 1 ticket to JSHeroes conference
**2nd** PRIZE: 1 ticket to JSHeroes conference
**3rd** PRIZE: Design and UI/UX books you’ll love
Each sticker will be voted on individually and all submissions will be ranked according to the number of votes. If a candidate has more than 1 sticker selected, only the top 1st sticker will receive a prize. 

**Competition schedule**
Sticker submission: **January 16 – 26**, 2019
JSHeroes team voting:  **January 27-28**, 2019
Winners announcement: **January 31**, 2019 

**Requirements**
• Each candidate can submit a maximum of **two** stickers.
• All images must be submitted as a **high-resolution**, Adobe Illustrator or Photoshop file **AND** a JPEG at 300 dpi or higher.

**Design criteria**
1. Stickers designs must be original work and incorporate the **JSHeroes logo**
2. JavaScript technology / community-related
3. Be simple, be funny if possible.

**Submission rules**
Please submit your stickers as a compressed or **zip** file to: welcome@jsheroes.io
Use email Subject: **JSHeroes stickers competition**
In the email body include: your **full name**, and any sticker explanation **notes**.
If you do not follow the submission rules your submission may not be successful.

**Permissions**
• Entrants assert that they either own or have the rights to all content used in their designs. Entrants using third-party material (i.e. material not owned by the entrant) must have received explicit permission from the owner to use these materials.
• Also, entrants grant the JSHeroes community **royalty-free**, perpetual, irrevocable, non-exclusive right and license to the images.
• Entrants will agree to authorize JSHeroes community members to use and share their stickers within the JSHeroes community for non-commercial and commercial use.
Feel free to share your stickers on Twitter with the **#jsheroesstickers** hashtag to get the buzz going about the contest.

**Good luck and have fun!**
JSHeroes Team

**Comment by jonattfin** [comment]
@claudmi How are the users getting to this page? I don't any link to it ... Maybe in the footer as we did for the adpot a jser?

**Comment by claudmi** [comment]
Yes, it can be the 1st link you see in the MORE INFO section in the footer.
We will need to remove the link when the contest ends.

**Comment by alexPopNicolae** [comment]
Just a suggestion...I think that the contest link is not very visible only in the footer and should be added also in other parts of the app, the header for example...but this depends on how important it is and how much priority it has...so I am waiting for suggestions.

**Comment by claudmi** [comment]
Thanks @alexPopNicolae good advice, let's add a new tab in the News section, titled Sticker Contest, position after CFP Closed.
Text>>
Announcing: JSHeroes Sticker Contest
Enter the sticker design competition to win cool stuff or just to have fun!
Find all the [details here](https://jsheroes.io/sticker-contest).
Good luck!

@aleretegan should we add a link to the Sticker Contest in the website header?
Could be good for visibility.

**Comment by claudmi** [comment]
@alexPopNicolae could you send me the link to take a look at the page?

**Comment by alexPopNicolae** [comment]
Hi  @claudmi,

https://jsheroesio-czdaqggqkw.now.sh/sticker-contest - check this link...it should take you to the page.

**Comment by claudmi** [comment]
@alexPopNicolae the cover photo looks pixelated, so I've replaced it in Zeplin as an asset, 
please replace it on the website as well.
Otherwise all looks good.
