### ISSUE TITLE
Add new Workshop 

### ISSUE THREAD

**Issue by aleretegan** [jsheroes/jsheroes.io#328]
**In Schedule Area > Workshops** Tab please add the following workshop:
 14:00 - 18:00 Custom React Native Modules for iOS and Android
Andrei Pfeiffer, Code Designer @ [e-spres-oh]

Picture: https://www.dropbox.com/s/6362an9a1xle034/IMG_0473x.jpg?dl=0

URL should point here: https://ti.to/cluj-javascripters/workshops-day-jsheroes-2019

On Workshop`s page please add the following details:

Custom React Native Modules for iOS and Android
Andrei Pfeiffer, Code Designer @ [e-spres-oh]

Half-Day Workshop, April 10th

Workshop Description *
This message will be displayed on the website. Please provide here whatever information you think is relevant to convince potential attendees to join this workshop. Feel free to include information about the curricula, objectives or any prerequisites. We will be able to email all the attendees with specific details if you need them to do something before the workshop.
React Native already offers a wide range of native features, thanks to its built-in modules and a ton of open source libraries.

But sometimes you might not find the exact solution you're looking for. The flexibility to build your own custom modules or extend existing libraries gives you a huge advantage in mobile apps development.

Diving into native code might feel very scary for web developers, and this advanced workshop is the proper cure for this problem.

In this advanced workshop we will:
* implement a simple native class (Swift for iOS & Java for Android)
* bridge it to React Native
* get access to it from JavaScript
* call native methods from JavaScript
* call JavaScript methods from native code

At the end of this workshop, native modules shouldn't feel so scary anymore. You will also understand better how React Native actually works under the hood and how JavaScript communicates with native code.

Attendees Prerequisite *
This is an advanced workshop and all participants should feel comfortable with both React and React Native. You should be able to run the "Hello World" application both on Android emulators from Android Studio and iOS simulators from Xcode (applies for Apple users).

You should have the following installed:
* Node.js v10+
* React Native Cli v2
* Android Studio v3.1+ & an emulator with API 26+
* Xcode 10.1 (for Apple users)

NOTE: native mobile experience is not required, but basic knowledge is nice to have.

Twitter @pfeiffer_andrei
GitHub https://github.com/andreipfeiffer/
Website / Blog https://medium.com/@andrei.pfeiffer

**Comment by aleretegan** [comment]
Please make the following changes:
1. la primul bullet ar trebui inchisa paranteza la final ")"
2. la final la NOTE, de inlocuit cu: "NOTE: native mobile experience is not required, but basic knowledge would definitely help."
3.Adaugare sectiune About the trainer:
Andrei Pfeiffer is a "designer / developer hybrid", specialized in UI development, both on web and mobile. He organizes tim.js, the local JavaScript meetup in Timisoara/RO & revo.js conference. He's also a public speaker, trainer, mentor and technical writer.

4.Schimbare poza cu https://www.dropbox.com/s/6362an9a1xle034/IMG_0473x.jpg?dl=0

**Comment by danielmocan** [comment]
@aleretegan I had to change the image( wrong size ).
I asked Andrei for a new image.
I did the modifications.

**Comment by danielmocan** [comment]
@aleretegan can I close this issue?
