### ISSUE TITLE
Change Metro logo 

### ISSUE THREAD

**Issue by aleretegan** [jsheroes/jsheroes.io#343]
We have a new logo for Metro, at a higher resolution
[MSys_Logo-centered.pdf](https://github.com/jsheroes/jsheroes.io/files/2827710/MSys_Logo-centered.pdf)

**Comment by danielmocan** [comment]
![metro-systems](https://user-images.githubusercontent.com/15091326/52265068-e8f9b900-293b-11e9-9fba-1b5715120ec7.png)

**Comment by danielmocan** [comment]
Fixed, I got another logo from the company.
