### ISSUE TITLE
Add a buy workshop tickets button on the hero image

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#355]
This is something that came up during today's meeting. Open for ideas, but I was thinking we could add a button bellow the main CTA. Don't really like it so far, so I'm really curios what others have in mind. The objective of this would be to promote the workshop tickets better.

<img width="1257" alt="screenshot 2019-02-11 at 21 18 59" src="https://user-images.githubusercontent.com/9945366/52587691-3cd83680-2e43-11e9-92a5-ecd18af44291.png">

**Comment by alexPopNicolae** [comment]
I think a better place would be to put it on the same line with ticket button and probably use a different color for it.

**Comment by alexnm** [comment]
@alexPopNicolae we also need to rename "Buy Your Ticket" to "Buy Your Conference Ticket"

**Comment by claudmi** [comment]
What do you think about this?
![home-tickets-buttons](https://user-images.githubusercontent.com/210512/52905165-f453bb00-323e-11e9-8252-fdb215fa5353.png)

**Comment by alexnm** [comment]
@aleretegan what do you think? since we discussed about this a few days ago

**Comment by claudmi** [comment]
@alexnm in the News section, in the Tickets tab we could also add something like this: 
Check out our [pre-conference workshops](https://jsheroes.io/#workshops-schedule) taught by a few of the smartest people we know.
but we need an anchor link to the WORKSHOPS tab in the Schedule section.

**Comment by alexnm** [comment]
@claudmi I like that, good idea!

@alexPopNicolae can you take this for the implementation? or maybe someone else?

**Comment by alexPopNicolae** [comment]
Hi! I will take care of it tonight

**Comment by claudmi** [comment]
@aleretegan @alexnm if we add a new tab called **Workshop Tickets** as the 1st tab in the News section, what can we do with the **Tickets** tab that's already in the News section? Can we remove it completely?

**Comment by claudmi** [comment]
@alexnm The simplest way is to add the **Buy Your Workshop Ticket** button, 
so I've added the design in Zeplin.

**Comment by alexPopNicolae** [comment]
I've added the button. Please check it on small screen also and tell me if it does not look right to you.

**Comment by alexPopNicolae** [comment]
I've added also the text to the news section under the tickets tab. I have made a small tweak to the text by adding the Also word...it made more sense in my head but if it os not ok I can remove it.

Have a good night!
