### ISSUE TITLE
In Menu replace Sponsors with link to Organizers

### ISSUE THREAD

**Issue by aleretegan** [jsheroes/jsheroes.io#381]
-replace in menu Sponsors with Organizers / Who's behind , whatever text fits better: https://jsheroes.io/organizers
-update Team page with Vlad Ionescu`s details - add him to Core team section (first one)
 Role: Volunteer,  no twitter handler
-change Alin Ilea's role from Webmaster to ACT trip organizer 
-change Anna Cojuhari`s title from Bannerman to Communication Advisor

**Comment by aleretegan** [comment]
![196D80E8-2093-4E3C-98F0-5F15F5E2A671-1](https://user-images.githubusercontent.com/19417706/56335407-12895900-61a5-11e9-92f9-75469786cd46.jpg)

**Comment by aleretegan** [comment]
Role: Volunteer
no twitter handler

**Comment by alinilea** [comment]
Please use this text for me: 'After Conf Trip organizer'
Thank you!

**Comment by claudmi** [comment]
Attached the b&w photo of Vlad

![vlad-ionescu](https://user-images.githubusercontent.com/210512/56495067-231b3580-64fd-11e9-8744-cd87e91b73a6.jpg)
