### ISSUE TITLE
photo gallery - prepare site for 2020

### ISSUE THREAD

**Issue by jonattfin** [jsheroes/jsheroes.io#386]
this is a subitem of: Prepare site for 2020 #385

two new rows of images should be added in the photos section - with the photos from 2019 and the videos from 2019 as links

**Comment by jonattfin** [comment]
@claudmi 

Regarding this #item:
two new rows of images should be added in the photos section - with the photos from 2019 and the videos from 2019 as links

I propose to have the photo gallery section always related to the previous edition, i.e. in this case have a photo gallery, and links to videos & photos from JSH 2019. The links to photos & videos from 2018 & 2017 can be included in the Highlights section of jsheroes.io/2018 and .../2017.
Does this sound ok? If so I'll create a mockup for the 2019 photo gallery section.

**Comment by jonattfin** [comment]
@claudmi : i agree with you, i would like to see those mockups :-), and i need a selection of pictures from 2019, pleasee :-))

**Comment by claudmi** [comment]
I'll upload mockups tonight

**Comment by jonattfin** [comment]
@claudmi : let's keep it only on this task

Attached the 2019 photo gallery mockup -- it's done in illustrator, so cannot be exported to Zeplin, but it should be fine, since you only have to replace the photos and edit the text/links.
![photo-gallery-1920px-section](https://user-images.githubusercontent.com/210512/58839877-d9794b00-8663-11e9-862f-ccd79a335760.png)

The photos are here:
[jsh-photo-gallery-2019.zip](https://github.com/jsheroes/jsheroes.io/files/3249771/jsh-photo-gallery-2019.zip)

Links:
2019 Photos: 
https://www.facebook.com/pg/jsheroes/photos/?tab=album&album_id=2275719352665968

2019 Videos:
https://www.youtube.com/watch?v=jdr9eQGq97g&list=PLB9NqTp0uKrR8WFXitMvLMGd-kGGZ4RkX

2019 Website:
we need to create https://jsheroes.io/2019
