### ISSUE TITLE
Refreshing on workshops pages

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#391]
When you go to a workshop page from the schedule tab, it loads fine, but when you refresh the page or when you access the workshop link from outside, the website gives an error. It's probably related to some data not being loaded.

**Comment by jonattfin** [comment]
I've looked a bit on this issue, locally everything is fine, but on the server not I've seen that the service worker throws some errors => this might cause the issue.

**Comment by alexnm** [comment]
cc @emimuresan, some service worker caching?

**Comment by emimuresan** [comment]
@alexnm i'll check it out this week.

**Comment by alexnm** [comment]
we need to upgrade to next 9 and get rid of the server implementation anyway, so I'll try to do that in #398
