### ISSUE TITLE
JSHeroes 2020 mascot bear page

### ISSUE THREAD

**Issue by emimuresan** [jsheroes/jsheroes.io#429]
Implement bear page.

* Accessible by: clicking on the bear image in the footer.
* Url should be: `/meet-ecma`
* Text should be: see @claudmi 's message on slack
* Images: `TBA` (should be attached to this issue)

Open question: Do we need a mock up or can we stitch something together and get UX approval?

**Comment by elizamaria** [comment]
Most of the information about the organization we will donate our money to should be from here: https://millionsoffriends.org/en/libearty/about-the-sanctuary/
