### ISSUE TITLE
Update stats on sponsors page

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#515]
Social media stats are outdated: https://jsheroes.io/become-a-sponsor

**Comment by inomag** [comment]
Hi @alexnm. Is this issue open for everybody? I went through the code and found the file where the changes need to be done.

**Comment by alexnm** [comment]
Hey @inomag sure, all contributions are welcome

**Comment by inomag** [comment]
Thanks, I will create a PR then

**Comment by alexnm** [comment]
Views: 110K
Hours: 10K (you can update minutes of content watched to hours)
