### ISSUE TITLE
Become a sponsor - page

### ISSUE THREAD

**Issue by oana-sipos** [jsheroes/jsheroes.io#53]
Create a manifesto page where we explain where we stand and that we definitely want to help companies to make the most out of JSHeroes, before, at and after the event. Also add ideas on how they can maximize their visibility at the event.

Checklist for this:
- [ ] Manifesto page on jsheroes.io
- [ ] Manifesto text
- [ ] A button for companies to contact us if they want to sponsor [ideally ask them to send with this request what they want to take out of this sponsorship]

**Comment by claudmi** [comment]
@oana-sipos cine scrie textul pentru Manifesto?

**Comment by oana-sipos** [comment]
Thanks for this draft @claudmi. Here are my suggestions for the intro part + some small remixes to your text. Feel free to mention if you don't agree with the changes :)

@alexnm @aleretegan how does this first draft sound? Feel free to feedback it, I am sure it could benefit from some polishing.

```
JSHeroes is an event by and for the JavaScript community, both local and international. Our aim is to provide top notch content to keep developers up to date with the latest technologies, as well as to help them level up their technical skills.

The conference itself is a perfect occasion to bring together international and local speakers, passionate developers and companies that believe in our mission. Whoever has organized a conference knows the amount of energy, time and financial resources that it requires. The financial support received from companies is helping us with keeping the price of a ticket to an acceptable level for the local market, as well as to offer a top-notch experience.

We want to enforce the educational part of the conference, this is definitely a place where you can meet new developers, learn about the market's demand and expectations. Being developers ourselves, we are fond of smart and non-intrusive promotional methods and materials. We can provide feedback and consultancy to get the most out of your participation at JSHeroes.

Become a supporter
If you believe in our mission and work, please consider becoming a financial supporter.

If you are interested in sponsoring JSHeroes 2018 please send an email at welcome@jsheroes.io with the following information:
•	name of organization
•	name of contact person
•	email address of contact person
•	your goals for the sponsorship

We will follow-up your e-mail and send you our current offer.

What you get?
•	Direct access to 600+ developpers
•	Venue to advertise your company, product, service to a group of passionate and dedicated developers
•	Opportunity to touch base with the community about your products or new ideas
•	The chance to increase your JavaScript Developer teams knowledge
```

**Comment by claudmi** [comment]
Let's call this page .../become-a-sponsor
I attached the mockups.
![become a sponsor mobile](https://user-images.githubusercontent.com/210512/35700560-faedea54-079b-11e8-9118-21868a0b1f8b.png)
![become a sponsor](https://user-images.githubusercontent.com/210512/35700561-fb1ad398-079b-11e8-87b6-80fcd260eef1.png)


Here is the final version of the text:

# **Become a Sponsor**
**JSHeroes** is an event by and for the JavaScript community, both local and international. Our aim is to provide top-notch content to keep developers up to date with the **latest technologies**, as well as to help them level up their technical skills.

The conference itself is a perfect occasion to bring together international and local speakers, passionate developers and companies that believe in our mission. Whoever has organized a conference knows the amount of **energy**, time and financial resources that it requires. 
The financial support received from companies is helping us offer a **high quality** experience, while also keeping the price of a ticket to an acceptable level for the local market.

We want to emphasize the **educational** aspect of the conference, this is definitely a place where you can meet new developers, learn about the market's demands and expectations. Being developers ourselves, we are fond of **smart** and non-intrusive promotional methods and materials. 
We can provide feedback and consultancy to get the most out of your participation at JSHeroes.

If you believe in our mission and work, please consider joining the team as a financial Supporter.

**Interested in sponsoring JSHeroes?**
Send us an email at welcome@jsheroes.io with the following information:

•	name of organization
•	name of contact person
•	email address of contact person
•	your goals for the sponsorship

We will follow-up and send you our current offer.

**What you get?**
•	Direct access to 600+ developpers
•	Venue to advertise your company, product, service to a group of passionate and dedicated 
developers
•	Opportunity to touch base with the community about your products or new ideas
•	The chance to increase your JavaScript developer team's knowledge

**Comment by claudmi** [comment]
To get to the page **.../become-a-sponsor** we need to add text and a link in the Sponsors section:
 or click **[here](jsheroes.io/become-a-sponsor)** to find out more.
![sponsors-mockup](https://user-images.githubusercontent.com/210512/35700805-b498c32a-079c-11e8-9059-ed2b0e37b6fd.png)

**Comment by oana-sipos** [comment]
Looks good for what we need now. Thank you @claudmi for all the work!

On the long term, I'd strive for something like what these guys say: https://www.mrngr.com/manifesto/ :)
