### ISSUE TITLE
Add link to Ecma in footer and update info

### ISSUE THREAD

**Issue by elizamaria** [jsheroes/jsheroes.io#530]
[Right ](https://jsheroes.io/meet-ecma) -> make this page more visible ( add a link to it in footer at lease)
- Update information on page: 

- sa apara si AMP in fata numelui Libearty, adica AMP Libearty. 
- Link-urile sunt: https://millionsoffriends.org/en/libearty/adopt-a-bear/ pentru adoptia virtuala si https://www.youtube.com/watch?v=V3aTpIxIGDg pentru streaming.

**Comment by danielmocan** [comment]
@elizamaria 
I added Meet Ecma link in the footer and added AMP in front of Libearty, please check jsheroes.io. If its ok please close the ticket.
