### ISSUE TITLE
Style text on Transparency report part 2

### ISSUE THREAD

**Issue by aleretegan** [jsheroes/jsheroes.io#553]
This year in June we had our first in-person event after the pandemics. For the 4th edition of JSHeroes we decided to go for a 1-day event, with only 300 participants, so that everyone feels safe to participate.

We strongly believe that the community model is the best environment for learning, so we’re publishing all the data about this conference, in full transparency, to make it easier for other communities to build on our knowledge and organize even better events.

As promised, we came back with some updates regarding the **conference’s budget**. It was calculated as to cover all the costs for the participants and the profit will be redirected to educational initiatives & next year's edition (according to the detailed plan at the end of the article).

In [our previous article](https://website-jsheroes.vercel.app/posts/2022-transparency-plan) we presented the estimates so we can all make an idea of what organizing a conference means in terms of costs (but not only) and now we’ve updated them and we got to some **conclusions** that we hope to be useful for other communities organizing a conference:

Summary:

- Cost - 32.853 EUR
- Money left - 19.147 EUR
- Attendees - 300
- Days - 1
- Speakers - 13

Expenses:

- Staff - 2.3K EUR (the cost is so low because most of the work is done by volunteers and we need extra help for accounting services and operations)
- Speakers (flight tickets, accommodation, trip, gift bags) - 8.2K EUR
- Venue + food & drinks (3 coffee breaks/day + 1 lunch/day for every attendee) - 9.4K EUR
- Photo-video services - 2.6K EUR
- Swag (stickers, badges), Promotional stuff (giveaways) - 4.6K EUR
- Promotional campaigns - 100 EUR
- Other services that cannot be covered by volunteers (e.g.: design, sketching during the conference) - 1.1K
- Tools subscriptions (CFP, hosting) - 250 EUR
- Venue services & design (Stage design - lights, scaffold, Barista, Photobooth) - 2.5K
- Fees (Ti.to, PayPal, Bank) - 1K EUR
- Costs that couldn’t be covered through partnerships (eg. ice-cream, water, gas) - 750 EUR

How did we plan to pay for all these things?

- Tickets - after estimating the costs, we’ve calculated the tickets price so as to cover the conference price but to keep our non-profit scope. We planned to have 240 tickets sold: 100 Early bird tickets * 90 EUR+VAT, 140 Regular tickets * 125 EUR + VAT — Total: 26.5K EUR

- Sponsors - whose only interest is to help the community grow by paying a fee for a special sponsorship package, recruitment-free, with only a few benefits as our purpose is not to get any kind of profit out of this but to get some help to organize a great event) * 2.000 EUR/sponsorship package

We kept the same sponsorship package as the year before and hoped companies will join us. And they did, even much more than we’ve expected. There were 12 companies sponsoring us, both from Romania and from abroad, so we are very thankful to: Evozon, Fortech, Cloudflight, Moqups, MCRO, CodeSandbox, DevNest, Victory Square Partners, Yonder, Accesa, Frequentis, tec:agency, Flowx.AI, Teleport. With their help we managed to raise 25.500 EUR.

The money left from the previous edition contributed a lot in removing the worries we had when starting to organize the 4th edition, as we were able to pay in advance for different services. This year’s budget looks better than planned, so besides the money we’re keeping to jump start 2023’s edition we are going to use the extra money to continue the plans we made for **helping the growth of the community**. The first event we’ll use them for is the JSHeroes Bootcamp, where we have opened our [call for mentors](https://forms.gle/ajQZepgHRx898P977) and besides that we’ll support the JSHeroes Meetups and a number of local NGOs that help children or underprivileged groups.

We hope you enjoyed our 2022 event and will **join us again in 2023**!
Keep an eye on social media for news on the content and the tickets going out on sale for next year.

**Comment by alexnm** [comment]
Done
