### ISSUE TITLE
Add the concept of keynote talk

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#72]
I'm adding this as a reference here as we want to have the first two talks from each day labeled as keynotes

**Comment by claudmi** [comment]
@alexnm Is this OK?
@danielmocan Do you need a SVG with the KEYNOTE label?
![mockup-keynote](https://user-images.githubusercontent.com/210512/44480514-0d8efc80-a64c-11e8-8ee2-e771c2abdb49.png)

**Comment by danielmocan** [comment]
@claudmi we can implement this without an SVG.

**Comment by alexnm** [comment]
this can be taken by someone else once we have the agenda ready (#240)

**Comment by alexnm** [comment]
I think the agenda works well without the keynote thing, I'll close this for now
